version: 2
updates:
  - package-ecosystem: github-actions
    directory: .github/workflows
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: js
    schedule:
      interval: weekly
