#!/bin/bash -e

if [[ ! -e /etc/default/firewall ]]; then
	cat <<-EOF > /etc/default/firewall
	WHITE_LIST="no"
	TCP_ALLOW="21 22 80 443"
	UDP_ALLOW=""
	EOF
fi

. /etc/default/firewall

[[ "${WHITE_LIST}" != "yes" ]] && echo "White-list firewall not enabled!" && exit 0

[[ "${TCP_ALLOW}" != "" ]] && for PORT in ${TCP_ALLOW}; do
	iptables -D INPUT -p tcp --dport ${PORT} -j ACCEPT >/dev/null 2>&1 || true
	iptables -I INPUT -p tcp --dport ${PORT} -j ACCEPT
done

[[ "${UDP_ALLOW}" != "" ]] && for PORT in ${UDP_ALLOW}; do
	iptables -D INPUT -p udp --dport ${PORT} -j ACCEPT >/dev/null 2>&1 || true
	iptables -I INPUT -p udp --dport ${PORT} -j ACCEPT
done

iptables -D INPUT -p tcp --source 127.0.0.1 -j ACCEPT >/dev/null 2>&1 || true
iptables -A INPUT -p tcp --source 127.0.0.1 -j ACCEPT
iptables -D INPUT -p tcp --dport 1:9999 -j DROP >/dev/null 2>&1 || true
iptables -A INPUT -p tcp --dport 1:9999 -j DROP

iptables -D INPUT -p udp --source 127.0.0.1 -j ACCEPT >/dev/null 2>&1 || true
iptables -A INPUT -p udp --source 127.0.0.1 -j ACCEPT
iptables -D INPUT -p udp --dport 1:9999 -j DROP >/dev/null 2>&1 || true
iptables -A INPUT -p udp --dport 1:9999 -j DROP

