# CMake generated Testfile for 
# Source directory: /home/user/out/cmake/Tests/CMakeLib
# Build directory: /home/user/out/cmake/1/Tests/CMakeLib
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[CMakeLib.testAssert]=] "/home/user/out/cmake/1/Tests/CMakeLib/CMakeLibTests" "testAssert")
set_tests_properties([=[CMakeLib.testAssert]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;97;add_test;/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testArgumentParser]=] "/home/user/out/cmake/1/Tests/CMakeLib/CMakeLibTests" "testArgumentParser")
set_tests_properties([=[CMakeLib.testArgumentParser]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;97;add_test;/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testCTestBinPacker]=] "/home/user/out/cmake/1/Tests/CMakeLib/CMakeLibTests" "testCTestBinPacker")
set_tests_properties([=[CMakeLib.testCTestBinPacker]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;97;add_test;/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testCTestResourceAllocator]=] "/home/user/out/cmake/1/Tests/CMakeLib/CMakeLibTests" "testCTestResourceAllocator")
set_tests_properties([=[CMakeLib.testCTestResourceAllocator]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;97;add_test;/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testCTestResourceSpec]=] "/home/user/out/cmake/1/Tests/CMakeLib/CMakeLibTests" "testCTestResourceSpec" "/home/user/out/cmake/Tests/CMakeLib")
set_tests_properties([=[CMakeLib.testCTestResourceSpec]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;97;add_test;/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testCTestResourceGroups]=] "/home/user/out/cmake/1/Tests/CMakeLib/CMakeLibTests" "testCTestResourceGroups")
set_tests_properties([=[CMakeLib.testCTestResourceGroups]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;97;add_test;/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testDebug]=] "/home/user/out/cmake/1/Tests/CMakeLib/CMakeLibTests" "testDebug")
set_tests_properties([=[CMakeLib.testDebug]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;97;add_test;/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testDocumentationFormatter]=] "/home/user/out/cmake/1/Tests/CMakeLib/CMakeLibTests" "testDocumentationFormatter")
set_tests_properties([=[CMakeLib.testDocumentationFormatter]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;97;add_test;/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testGccDepfileReader]=] "/home/user/out/cmake/1/Tests/CMakeLib/CMakeLibTests" "testGccDepfileReader" "/home/user/out/cmake/Tests/CMakeLib")
set_tests_properties([=[CMakeLib.testGccDepfileReader]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;97;add_test;/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testGeneratedFileStream]=] "/home/user/out/cmake/1/Tests/CMakeLib/CMakeLibTests" "testGeneratedFileStream")
set_tests_properties([=[CMakeLib.testGeneratedFileStream]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;97;add_test;/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testJSONHelpers]=] "/home/user/out/cmake/1/Tests/CMakeLib/CMakeLibTests" "testJSONHelpers")
set_tests_properties([=[CMakeLib.testJSONHelpers]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;97;add_test;/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testRST]=] "/home/user/out/cmake/1/Tests/CMakeLib/CMakeLibTests" "testRST" "/home/user/out/cmake/Tests/CMakeLib")
set_tests_properties([=[CMakeLib.testRST]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;97;add_test;/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testRange]=] "/home/user/out/cmake/1/Tests/CMakeLib/CMakeLibTests" "testRange")
set_tests_properties([=[CMakeLib.testRange]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;97;add_test;/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testOptional]=] "/home/user/out/cmake/1/Tests/CMakeLib/CMakeLibTests" "testOptional")
set_tests_properties([=[CMakeLib.testOptional]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;97;add_test;/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testPathResolver]=] "/home/user/out/cmake/1/Tests/CMakeLib/CMakeLibTests" "testPathResolver")
set_tests_properties([=[CMakeLib.testPathResolver]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;97;add_test;/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testString]=] "/home/user/out/cmake/1/Tests/CMakeLib/CMakeLibTests" "testString")
set_tests_properties([=[CMakeLib.testString]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;97;add_test;/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testStringAlgorithms]=] "/home/user/out/cmake/1/Tests/CMakeLib/CMakeLibTests" "testStringAlgorithms")
set_tests_properties([=[CMakeLib.testStringAlgorithms]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;97;add_test;/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testSystemTools]=] "/home/user/out/cmake/1/Tests/CMakeLib/CMakeLibTests" "testSystemTools")
set_tests_properties([=[CMakeLib.testSystemTools]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;97;add_test;/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testUTF8]=] "/home/user/out/cmake/1/Tests/CMakeLib/CMakeLibTests" "testUTF8")
set_tests_properties([=[CMakeLib.testUTF8]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;97;add_test;/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testXMLParser]=] "/home/user/out/cmake/1/Tests/CMakeLib/CMakeLibTests" "testXMLParser")
set_tests_properties([=[CMakeLib.testXMLParser]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;97;add_test;/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testXMLSafe]=] "/home/user/out/cmake/1/Tests/CMakeLib/CMakeLibTests" "testXMLSafe")
set_tests_properties([=[CMakeLib.testXMLSafe]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;97;add_test;/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testFindPackageCommand]=] "/home/user/out/cmake/1/Tests/CMakeLib/CMakeLibTests" "testFindPackageCommand")
set_tests_properties([=[CMakeLib.testFindPackageCommand]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;97;add_test;/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testUVHandlePtr]=] "/home/user/out/cmake/1/Tests/CMakeLib/CMakeLibTests" "testUVHandlePtr")
set_tests_properties([=[CMakeLib.testUVHandlePtr]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;97;add_test;/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testUVJobServerClient]=] "/home/user/out/cmake/1/Tests/CMakeLib/CMakeLibTests" "testUVJobServerClient")
set_tests_properties([=[CMakeLib.testUVJobServerClient]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;97;add_test;/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testUVProcessChain]=] "/home/user/out/cmake/1/Tests/CMakeLib/CMakeLibTests" "testUVProcessChain" "/home/user/out/cmake/1/Tests/CMakeLib/testUVProcessChainHelper")
set_tests_properties([=[CMakeLib.testUVProcessChain]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;97;add_test;/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testUVRAII]=] "/home/user/out/cmake/1/Tests/CMakeLib/CMakeLibTests" "testUVRAII")
set_tests_properties([=[CMakeLib.testUVRAII]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;97;add_test;/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testUVStreambuf]=] "/home/user/out/cmake/1/Tests/CMakeLib/CMakeLibTests" "testUVStreambuf" "/home/user/out/cmake/1/bin/cmake")
set_tests_properties([=[CMakeLib.testUVStreambuf]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;97;add_test;/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testCMExtMemory]=] "/home/user/out/cmake/1/Tests/CMakeLib/CMakeLibTests" "testCMExtMemory")
set_tests_properties([=[CMakeLib.testCMExtMemory]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;97;add_test;/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testCMExtAlgorithm]=] "/home/user/out/cmake/1/Tests/CMakeLib/CMakeLibTests" "testCMExtAlgorithm")
set_tests_properties([=[CMakeLib.testCMExtAlgorithm]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;97;add_test;/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testCMExtEnumSet]=] "/home/user/out/cmake/1/Tests/CMakeLib/CMakeLibTests" "testCMExtEnumSet")
set_tests_properties([=[CMakeLib.testCMExtEnumSet]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;97;add_test;/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testList]=] "/home/user/out/cmake/1/Tests/CMakeLib/CMakeLibTests" "testList")
set_tests_properties([=[CMakeLib.testList]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;97;add_test;/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testCMakePath]=] "/home/user/out/cmake/1/Tests/CMakeLib/CMakeLibTests" "testCMakePath")
set_tests_properties([=[CMakeLib.testCMakePath]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;97;add_test;/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testDebuggerAdapter]=] "/home/user/out/cmake/1/Tests/CMakeLib/CMakeLibTests" "testDebuggerAdapter")
set_tests_properties([=[CMakeLib.testDebuggerAdapter]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;97;add_test;/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testDebuggerAdapterPipe]=] "/home/user/out/cmake/1/Tests/CMakeLib/CMakeLibTests" "testDebuggerAdapterPipe")
set_tests_properties([=[CMakeLib.testDebuggerAdapterPipe]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;97;add_test;/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testDebuggerBreakpointManager]=] "/home/user/out/cmake/1/Tests/CMakeLib/CMakeLibTests" "testDebuggerBreakpointManager")
set_tests_properties([=[CMakeLib.testDebuggerBreakpointManager]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;97;add_test;/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testDebuggerVariables]=] "/home/user/out/cmake/1/Tests/CMakeLib/CMakeLibTests" "testDebuggerVariables")
set_tests_properties([=[CMakeLib.testDebuggerVariables]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;97;add_test;/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testDebuggerVariablesHelper]=] "/home/user/out/cmake/1/Tests/CMakeLib/CMakeLibTests" "testDebuggerVariablesHelper")
set_tests_properties([=[CMakeLib.testDebuggerVariablesHelper]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;97;add_test;/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testDebuggerVariablesManager]=] "/home/user/out/cmake/1/Tests/CMakeLib/CMakeLibTests" "testDebuggerVariablesManager")
set_tests_properties([=[CMakeLib.testDebuggerVariablesManager]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;97;add_test;/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testDebuggerThread]=] "/home/user/out/cmake/1/Tests/CMakeLib/CMakeLibTests" "testDebuggerThread")
set_tests_properties([=[CMakeLib.testDebuggerThread]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;97;add_test;/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testDebuggerNamedPipe-Project]=] "/home/user/out/cmake/1/Tests/CMakeLib/testDebuggerNamedPipe" "/home/user/out/cmake/1/bin/cmake" "/home/user/out/cmake/Tests/CMakeLib/DebuggerSample" "/home/user/out/cmake/1/Tests/CMakeLib/DebuggerSample")
set_tests_properties([=[CMakeLib.testDebuggerNamedPipe-Project]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;120;add_test;/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testDebuggerNamedPipe-Script]=] "/home/user/out/cmake/1/Tests/CMakeLib/testDebuggerNamedPipe" "/home/user/out/cmake/1/bin/cmake" "/home/user/out/cmake/Tests/CMakeLib/DebuggerSample/script.cmake")
set_tests_properties([=[CMakeLib.testDebuggerNamedPipe-Script]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;120;add_test;/home/user/out/cmake/Tests/CMakeLib/CMakeLists.txt;0;")
subdirs("PseudoMemcheck")
