#!/bin/bash

set -e

if [ $# -ne 2 ]; then
    echo "Usage: ./delete_image <min_img_size> <max_img_size>"
    exit 1
fi

#!/bin/bash

while true; do
    # 删除大小小于$1M和大于$2M的图像
    find . -type f \( -name "*.jpeg" -o -name "*.png" -o -name "*.jpg" \) -size -"$1"M -print -delete
    find . -type f \( -name "*.jpeg" -o -name "*.png" -o -name "*.jpg" \) -size +"$2"M -print -delete

    # 计算当前图像数量
    LAST_IMG="$(find . -type f \( -name '*.jpeg' -o -name '*.png' -o -name '*.jpg' \) | wc -l)"

    # 检查图像数量是否满足需求
    if [ "$LAST_IMG" -lt "$number" ]; then
        # 运行下载脚本
        bash ../image_down $(pwd) $(($number - $LAST_IMG))
    else
        # 如果满足需求，跳出循环
        break
    fi
done
