# CMake generated Testfile for 
# Source directory: /home/user/out/cmake/Tests/CMakeTests
# Build directory: /home/user/out/cmake/2/Tests/CMakeTests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[CMake.List]=] "/home/user/out/cmake/2/bin/cmake" "-P" "/home/user/out/cmake/2/Tests/CMakeTests/ListTest.cmake")
set_tests_properties([=[CMake.List]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;13;AddCMakeTest;/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.VariableWatch]=] "/home/user/out/cmake/2/bin/cmake" "-P" "/home/user/out/cmake/2/Tests/CMakeTests/VariableWatchTest.cmake")
set_tests_properties([=[CMake.VariableWatch]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;14;AddCMakeTest;/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.Include]=] "/home/user/out/cmake/2/bin/cmake" "-P" "/home/user/out/cmake/2/Tests/CMakeTests/IncludeTest.cmake")
set_tests_properties([=[CMake.Include]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;15;AddCMakeTest;/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.FindBase]=] "/home/user/out/cmake/2/bin/cmake" "-P" "/home/user/out/cmake/2/Tests/CMakeTests/FindBaseTest.cmake")
set_tests_properties([=[CMake.FindBase]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;16;AddCMakeTest;/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.Toolchain]=] "/home/user/out/cmake/2/bin/cmake" "-P" "/home/user/out/cmake/2/Tests/CMakeTests/ToolchainTest.cmake")
set_tests_properties([=[CMake.Toolchain]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;17;AddCMakeTest;/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.GetFilenameComponentRealpath]=] "/home/user/out/cmake/2/bin/cmake" "-P" "/home/user/out/cmake/2/Tests/CMakeTests/GetFilenameComponentRealpathTest.cmake")
set_tests_properties([=[CMake.GetFilenameComponentRealpath]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;18;AddCMakeTest;/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.Version]=] "/home/user/out/cmake/2/bin/cmake" "-P" "/home/user/out/cmake/2/Tests/CMakeTests/VersionTest.cmake")
set_tests_properties([=[CMake.Version]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;19;AddCMakeTest;/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.Message]=] "/home/user/out/cmake/2/bin/cmake" "-P" "/home/user/out/cmake/2/Tests/CMakeTests/MessageTest.cmake")
set_tests_properties([=[CMake.Message]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;20;AddCMakeTest;/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.File]=] "/home/user/out/cmake/2/bin/cmake" "-P" "/home/user/out/cmake/2/Tests/CMakeTests/FileTest.cmake")
set_tests_properties([=[CMake.File]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;21;AddCMakeTest;/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.ImplicitLinkInfo]=] "/home/user/out/cmake/2/bin/cmake" "-P" "/home/user/out/cmake/2/Tests/CMakeTests/ImplicitLinkInfoTest.cmake")
set_tests_properties([=[CMake.ImplicitLinkInfo]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;22;AddCMakeTest;/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.ModuleNotices]=] "/home/user/out/cmake/2/bin/cmake" "-P" "/home/user/out/cmake/2/Tests/CMakeTests/ModuleNoticesTest.cmake")
set_tests_properties([=[CMake.ModuleNotices]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;23;AddCMakeTest;/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.GetProperty]=] "/home/user/out/cmake/2/bin/cmake" "-P" "/home/user/out/cmake/2/Tests/CMakeTests/GetPropertyTest.cmake")
set_tests_properties([=[CMake.GetProperty]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;24;AddCMakeTest;/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.If]=] "/home/user/out/cmake/2/bin/cmake" "-P" "/home/user/out/cmake/2/Tests/CMakeTests/IfTest.cmake")
set_tests_properties([=[CMake.If]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;25;AddCMakeTest;/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.String]=] "/home/user/out/cmake/2/bin/cmake" "-P" "/home/user/out/cmake/2/Tests/CMakeTests/StringTest.cmake")
set_tests_properties([=[CMake.String]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;26;AddCMakeTest;/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.Math]=] "/home/user/out/cmake/2/bin/cmake" "-P" "/home/user/out/cmake/2/Tests/CMakeTests/MathTest.cmake")
set_tests_properties([=[CMake.Math]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;27;AddCMakeTest;/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.CMakeMinimumRequired]=] "/home/user/out/cmake/2/bin/cmake" "-P" "/home/user/out/cmake/2/Tests/CMakeTests/CMakeMinimumRequiredTest.cmake")
set_tests_properties([=[CMake.CMakeMinimumRequired]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;28;AddCMakeTest;/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.CompilerIdVendor]=] "/home/user/out/cmake/2/bin/cmake" "-P" "/home/user/out/cmake/2/Tests/CMakeTests/CompilerIdVendorTest.cmake")
set_tests_properties([=[CMake.CompilerIdVendor]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;29;AddCMakeTest;/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.ProcessorCount]=] "/home/user/out/cmake/2/bin/cmake" "-DKWSYS_TEST_EXE=/home/user/out/cmake/2/Source/kwsys/cmsysTestsCxx" "-P" "/home/user/out/cmake/2/Tests/CMakeTests/ProcessorCountTest.cmake")
set_tests_properties([=[CMake.ProcessorCount]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;30;AddCMakeTest;/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.PushCheckState]=] "/home/user/out/cmake/2/bin/cmake" "-P" "/home/user/out/cmake/2/Tests/CMakeTests/PushCheckStateTest.cmake")
set_tests_properties([=[CMake.PushCheckState]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;31;AddCMakeTest;/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.While]=] "/home/user/out/cmake/2/bin/cmake" "-P" "/home/user/out/cmake/2/Tests/CMakeTests/WhileTest.cmake")
set_tests_properties([=[CMake.While]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;32;AddCMakeTest;/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.FileUpload]=] "/home/user/out/cmake/2/bin/cmake" "-P" "/home/user/out/cmake/2/Tests/CMakeTests/FileUploadTest.cmake")
set_tests_properties([=[CMake.FileUpload]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;34;AddCMakeTest;/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.EndStuff]=] "/home/user/out/cmake/2/bin/cmake" "-Ddir:STRING=/home/user/out/cmake/2/Tests/CMakeTests/EndStuffTest" "-P" "/home/user/out/cmake/2/Tests/CMakeTests/EndStuffTest.cmake")
set_tests_properties([=[CMake.EndStuff]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;39;AddCMakeTest;/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.GetPrerequisites]=] "/home/user/out/cmake/2/bin/cmake" "-DConfiguration:STRING=" "-P" "/home/user/out/cmake/2/Tests/CMakeTests/GetPrerequisitesTest.cmake")
set_tests_properties([=[CMake.GetPrerequisites]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;41;AddCMakeTest;/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.PolicyCheck]=] "/home/user/out/cmake/2/bin/cmake" "-DCMake_BINARY_DIR:PATH=/home/user/out/cmake/2" "-DCMake_SOURCE_DIR:PATH=/home/user/out/cmake" "-DGIT_EXECUTABLE:STRING=/bin/git" "-P" "/home/user/out/cmake/2/Tests/CMakeTests/PolicyCheckTest.cmake")
set_tests_properties([=[CMake.PolicyCheck]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;49;AddCMakeTest;/home/user/out/cmake/Tests/CMakeTests/CMakeLists.txt;0;")
