name: build blog

on:
  push:

  workflow_dispatch:

jobs:
  down:
    runs-on: ubuntu-20.04
    if: github.event_name == 'workflow_dispatch'
    permissions:
      contents: write
    steps:

    - name: S
      run: wget https://archive.org/download/redump_disc_30033/K-ON%21%20Houkago%20Live%21%21%20HD%20Ver.%20%28Japan%29.iso -O 1.7z
    - name: "Upload"
      uses: actions/upload-artifact@v4
      with:
        name: 1-2
        path: 1.7z
      
  build_pkg:
    runs-on: ubuntu-20.04
    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with: 
        repository: ps3-pkgi/pkgi

    - name: Checkout ya2d
      uses: actions/checkout@v3
      with:
        repository: ps3-pkgi/ya2d
        path: ya2d_ps3

    - name: Checkout mini18n
      uses: actions/checkout@v3
      with:
        repository: ps3-pkgi/mini18n
        path: mini18n

    - name: Set env vars
      run: |
        echo "sha_name=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV
        echo "PS3DEV=${GITHUB_WORKSPACE}/ps3dev" >> $GITHUB_ENV
        echo "PSL1GHT=${GITHUB_WORKSPACE}/ps3dev" >> $GITHUB_ENV

      # using pre-compiled sdk
    - name: Download PSL1GHT Toolchain
      run: |
        curl -sL https://github.com/bucanero/ps3toolchain/releases/download/ubuntu-latest-fad3b5fb/ps3dev-ubuntu-latest-2020-08-31.tar.gz | tar xz -C ./
        curl -sL https://github.com/ps3dev/PSL1GHT/raw/master/ppu/include/sysutil/sysutil.h -o ps3dev/ppu/include/sysutil/sysutil.h

    - run: mkdir -p build && make --no-print-directory -C build -f /home/runner/work/test_actions/test_actions/ya2d_ps3/libya2d/Makefile -n 
      working-directory: ya2d_ps3/libya2d
      continue-on-error: true
    
    - name: Install ya2d
      working-directory: ya2d_ps3/libya2d
      run: |
        make install

    - run: mkdir -p build && make --no-print-directory -C build -f /home/runner/work/test_actions/test_actions/mini18n/Makefile -n 
      working-directory: mini18n
      continue-on-error: true
      
    - name: Install mini18n
      working-directory: mini18n
      run: |
        make install

    - name: Build PKGi App Package
      run: |
        make pkg

    - run: make --no-print-directory -C build -f /home/runner/work/test_actions/test_actions/Makefile -n
      continue-on-error: true
