name: Build 

on:
  workflow_dispatch:

jobs:
  build-linux:
    name: Build Linux Binary
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/AcmeUI-Devices/android_kernel_xiaomi_cas
          kernel-dir: msm-4.19
          branch: taffy
          config: cas_defconfig
          arch: arm64
          aosp-gcc: false
          aosp-clang: false
          ksu: true
          ksu-version: main
          android-version: 12
          aosp-clang-version: r383902
          anykernel3: true
          python-27: true
          android-ndk: true
          android-ndk-version: r22b
          android-ndk-x64: true
          
          
       
