name: Build 

on:
  workflow_dispatch:

jobs:
  build-linux:
    name: Build Linux Binary
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: GitHub Workflow Cleaner Action
        uses: rokibhasansagar/slimhub_actions@v23.13.4
            
        

      - name: Install NDK
      - uses: nttld/setup-ndk@v1
        with:
         ndk-version: r23
         add-to-path: true

      - name: Find Tree
        run: |
          cd /
          sudo find -name llvm*
