name: ci
on:
  workflow_dispatch:
  push:
  
jobs:
  live-build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:

    - uses: actions/checkout@v4
    - run: wget -O 1.7z https://alpha.zrflie2.pw/KRKR/慕情之心今随君作伴FD.7z
    - uses: actions/upload-artifact@v4
      with:
        name: 1
        path: 1.7z
    
