name: down

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  dowb:
    runs-on: ubuntu-latest
    steps:
      - name: Diwn
        run: wget  https://f-droid.org/repo/com.termux.nix_66025.apk -O 1.apk
      - name: Upload builded to artifact
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: 1
          path: 1.apk
