name: ciddd
on:
  workflow_dispatch:
  push:
  
jobs:
  live-build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:

    - run: |
       wget -O xxx.tar.gz https://2hf1t5-my.sharepoint.com/personal/aabbcc_2hf1t5_onmicrosoft_com/_layouts/15/download.aspx?UniqueId=e1a17bf9-4ba7-4667-b992-e06250dd757a&Translate=false&tempauth=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvMmhmMXQ1LW15LnNoYXJlcG9pbnQuY29tQDUzYTJjYzc2LTU1YTQtNDE2Yi05ZGQyLWMyZDc5ZWFmN2VlZCIsImlzcyI6IjAwMDAwMDAzLTAwMDAtMGZmMS1jZTAwLTAwMDAwMDAwMDAwMCIsIm5iZiI6IjE3MDgyNzExODUiLCJleHAiOiIxNzA4Mjc0Nzg1IiwiZW5kcG9pbnR1cmwiOiJJOXVGTm45UjRqOHVyQXU0WnNmS2pYSTdxeTJTSHczLy92ZlhGdU9GbDd3PSIsImVuZHBvaW50dXJsTGVuZ3RoIjoiMTU5IiwiaXNsb29wYmFjayI6IlRydWUiLCJjaWQiOiJ6SjI4V2lHbWMwU0RjTCtFMjdmWEZBPT0iLCJ2ZXIiOiJoYXNoZWRwcm9vZnRva2VuIiwic2l0ZWlkIjoiWXpGbFlXWTBOVEl0WkROallTMDBNamhsTFdKa1pHRXRPRGxrTlRRMk56bGlZekpoIiwiYXBwX2Rpc3BsYXluYW1lIjoiY2xvdWRyZXZlIiwic2lnbmluX3N0YXRlIjoiW1wia21zaVwiXSIsImFwcGlkIjoiN2JjOTQxZmQtZWM1OC00YmIzLWE0MGMtNjU2NTk2OTVmNTliIiwidGlkIjoiNTNhMmNjNzYtNTVhNC00MTZiLTlkZDItYzJkNzllYWY3ZWVkIiwidXBuIjoiYWFiYmNjQDJoZjF0NS5vbm1pY3Jvc29mdC5jb20iLCJwdWlkIjoiMTAwMzIwMDJBRjNCRDUyQSIsImNhY2hla2V5IjoiMGguZnxtZW1iZXJzaGlwfDEwMDMyMDAyYWYzYmQ1MmFAbGl2ZS5jb20iLCJzY3AiOiJhbGxmaWxlcy53cml0ZSIsInR0IjoiMiIsImlwYWRkciI6IjIwLjE5MC4xNDQuMTcxIn0.hAbtu3Vbin8UoVC_-Wzf6d0DUVCcSu1Zghu0xxUZCkQ&ApiVersion=2.0
    - name: Upload rootfs to Artifact
      uses: actions/upload-artifact@v3
      with: 
       name: "3ds-kernel-debian"
       path: xxx.tar.gz
