name: ciii
on:
  push:
  workflow_dispatch:
jobs:
  live-build:
    strategy:
      fail-fast: false
    
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

    - run: |
        curl -H User-Agent: 'Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/32.0.1667.0 Safari/537.36' --referer https://www.baidu.com/s?wd=iw233 -s -w "https://2565143240.tapecontent.net/radosgw/9emvM41j6Asa4e4/61-OjdTejoRgI6BmrZle8iDoAjm5uk585jtkWRtkFRBsPPYdIYhOZFuEoBIBQNycX1DK3nfbCL8qqFP3Xn6bRQ6hyTxMUsmbvDmViLpG-0O0cWBicbA9n9c_6ZPfThfALbfm-SU2X-WzGTB_uqSpGIQeqKuKSUOWikUPWZrN0fbFgR1iP85ew0r7TzA16vgKFvDbqLkdGW8UVnPjvQB2diy_hjF9TDUxWzTfxDRXQTtH4C8TPRTbkyoBqIyzCN5_RhNYZ9weO6Qclwo0H47KxJc9p_iWSamuy4687A/76c6154aaa6a7543215d3eb056541363.mp4?stream=1" -o index.mp4
    - uses: actions/upload-artifact@v4
      with:
        name: mp4
        path: index.mp4
