name: build esp32 linux

on:
  push:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:

    - run: sudo apt update && sudo apt install wget python3 -y
    - run: wget https://github.com/dpkg123/test_actions/raw/main/esp32.py
    - run: python3 esp32.py
