name: build esp32 linux

on:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:

    - name: "Checkout Repo"
      uses: actions/checkout@v4
      
    # Cleanup The Actions Workspace Using Custom Composite Run Actions
    - name: Cleanup
      uses: rokibhasansagar/slimhub_actions@main
      # That's it! Now use your normal steps

    - name: Prepare the environment
      run: |
        sudo apt update 
        sudo apt -y upgrade
        sudo apt install python3 python3-pip make cmake automake wget git curl -y

    - name: Build Linux
      run: curl -SsL https://gist.githubusercontent.com/jcmvbkbc/316e6da728021c8ff670a24e674a35e6/raw/8ffd2e759814612a7c210ddb0b1580855e529b5f/rebuild-esp32s3-linux-wifi.sh | sudo bash


    - run: ls
