name: build esp32 linux

on:
  push:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:

    - uses: dabao1955/clone-github-repo-action@main
      with:
        depth: 1
        branch: 'master'
        owner: 'AndreRH'
        repository: 'hangover'
        submodule: false
        path-to-clone: 'hangover-git'
