name: Build rootfs

on:
  push:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v4
        with:
          repository: dpkg123/pmaports
          submodules: true
          path: pmaports
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup pmbootstrap
        run: |
          sudo mv -v pmaports /home/runner/
          git clone https://gitlab.com/postmarketOS/pmbootstrap --depth=1
          cd pmbootstrap
          chmod +x pmbootstrap.py
          #sudo rm /usr/bin/pmbootstrap
          #sudo ln -sfv ./pmbootstrap.py /usr/bin/pmbootstrap
          
      - name: Initialize pmbootstrap
        run: |
           sudo aria2c  https://github.com/dpkg123/test_actions/raw/main/pmbootstrap_v3.cfg
           sudo mv pmbootstrap_v3.cfg -v /home/runner/.config/pmbootstrap_v3.cfg
           sudo chmod 777 -v /home/runner/.config/pmbootstrap_v3.cfg
           yes '' | ./pmbootstrap/pmbootstrap.py --details-to-stdout init
           #printf "%s\n" "edge" "xiaomi" "raphael" "user" "xfce4" "n" "none" "en_US" "xiaomi-raphael" "y" | ./pmbootstrap/pmbootstrap.py -q init

      - name: Build packages
        run: yes '123456' | ./pmbootstrap/pmbootstrap.py install --android-recovery-zip
