name: Build rootfs

on:
  push:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v4
        with:
          repository: dpkg123/pmaports
          path: ./pmaports
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup pmbootstrap
        run: |
          mv pmaports $HOME/
          git clone https://gitlab.com/postmarketOS/pmbootstrap --depth=1
          cd pmbootstrap
          sudo ln -s ./pmbootstrap.py /usr/bin/pmbootstrap
          
      - name: Initialize pmbootstrap
        run: printf "%s\n" "edge" "xiaomi" "raphael" "user" "xfce4" "n" "none" "en_US" "xiaomi-raphael" "y" | pmbootstrap --aports=$PWD/pmaports -q init

      - name: Build rootfs
        run: yes "123456" | pmbootstrap --aports=$PWD/pmaports -q install --android-recovery-zip
