name: build Serenity

on:

  workflow_dispatch:

jobs:
  build-iso:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:

    - name: clean
      uses: rokibhasansagar/slimhub_actions@main
        
    - name: "Checkout Repo"
      uses: actions/checkout@v4
      with: 
        repository: serenityos/serenity
        #repository: mos9527/mages-tools
        fetch-depth: 2
        submodules: true

    - name: Install dep
      run: |
        sudo apt-get update
        sudo apt install libgtk-3-dev libpixman-1-dev libsdl2-dev libslirp-dev libspice-server-dev qemu-system-x86 bash cmake curl e2fsprogs gawk genext2fs git ninja-build patch python3 rsync
        sudo apt install build-essential cmake curl libmpfr-dev libmpc-dev libgmp-dev e2fsprogs ninja-build qemu-system-gui qemu-system-x86 qemu-utils ccache rsync unzip texinfo libssl-dev
        #sudo ln -sv /proc/self/mounts /etc/mtab
    - name: Build
      run: bash -x Meta/serenity.sh run
        
