name: build Serenity

on:

  workflow_dispatch:
  push:

jobs:
  build-iso:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:

    - name: clean
      uses: rokibhasansagar/slimhub_actions@main
        
    - name: "Checkout Repo"
      uses: actions/checkout@v4
      with: 
        repository: serenityos/serenity
        #repository: mos9527/mages-tools
        fetch-depth: 2
        submodules: true

    - name: Install dep
      run: |
        sudo apt-get update
        sudo apt install libgtk-3-dev libpixman-1-dev libsdl2-dev libslirp-dev libspice-server-dev \
        bash ccache cmake curl e2fsprogs gawk genext2fs git ninja-build patch python3 rsync \
        build-essential cmake curl libmpfr-dev libmpc-dev libgmp-dev e2fsprogs ninja-build qemu-system-gui \
        qemu-system-x86 qemu-utils ccache rsync unzip texinfo libssl-dev \
        qt6-3d-dev qt6-shader-baker qt6-quick3d-dev qt6-designer-abi qt6-webengine-dev qt6-datavisualization-dev qt6-tools-dev qt6-wayland qt6-base-dev-tools libqt6core6 libqt6qml6 libqt6uitools6 libqt6webenginecore6
        #sudo ln -sv /proc/self/mounts /etc/mtab
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        create-symlink: true
        max-size: 4G
        key: b9897102d03247fb031d61a4efb9ade1dbded207
    
    - name: Build linker
      run: |
        export USE_CCACHE=1
        CXX=g++ bash Toolchain/BuildJakt.sh lagom
        CXX=g++ bash Toolchain/BuildMold.sh lagom
    - name: Build Toolchain
      run: |
        export USE_CCACHE=1
        bash Toolchain/BuildGNU.sh --ci
    - name: Configure
      run: |
        export USE_CCACHE=1
        cmake -GNinja -S Meta/CMake/Superbuild -B Build/superbuild-x86_64 -DSERENITY_ARCH=x86_64 -DSERENITY_TOOLCHAIN=GNU \
        -DENABLE_NETWORK_DOWNLOADS=on -DENABLE_ACCELERATED_GRAPHICS=on -DBUILD_EVERYTHING=on -DENABLE_JAKT=on -DENABLE_KERNEL_LTO=on \
        -DBUILD_LAGOM=on -DENABLE_MOLD_LINKER=on -DCMAKE_ASM_COMPILER=gcc -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ \
        -DWASM_SPEC_TEST_SKIP_FORMATTING=ON -DENABLE_LAGOM_LADYBIRD=ON -DENABLE_USERSPACE_COVERAGE_COLLECTION=OFF 
    - name: Build base system
      run: |
        export USE_CCACHE=1
        cmake --build Build/superbuild-x86_64
    - name: Build ports
      run: |
        export USE_CCACHE=1
        cd Build/superbuild-x86_64
        ninja configure-components
        ninja install-ports
        ninja all_generated
    - name: Enable the Ladybird Qt chrome
      working-directory: ${{ github.workspace }}/Meta/Lagom
      run: |
        export USE_CCACHE=1
        cmake -B Build -DENABLE_QT=ON -GNinja

    - name: Build the Ladybird Qt chrome
      working-directory: ${{ github.workspace }}/Meta/Lagom/Build
      run: |
        export USE_CCACHE=1
        cmake --build .

    - name: Build image
      run: |
        export USE_CCACHE=1
        cd Build/superbuild-x86_64
        ninja grub-image
        ls
        
        
